sonar.projectKey=proyecto_web
sonar.sources=website
sonar.language=py
sonar.host.url=http://localhost:9000
sonar.token=sqp_539171890b749196dda4967e9e1dc7aea1d23d9b
sonar.python.coverage.reportPaths=coverage.xml
